# Generated by Django 5.1.1 on 2024-09-25 16:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('environment', 'Environment'), ('technology', 'Technology'), ('design', 'Design'), ('culture', 'Culture'), ('business', 'Business'), ('politics', 'Politics'), ('travel', 'Travel')], default='technology', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='note',
            name='excerpt',
            field=models.CharField(default='This is a default excerpt.', max_length=150),
        ),
        migrations.AddField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='location',
            field=models.CharField(default='Unknown location', max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.ImageField(default='default_event_photo.jpg', upload_to='notes_photos/'),
        ),
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.CharField(default='This is a default slug.', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_notes', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_object', to='api.note')),
            ],
        ),
    ]
