# Generated by Django 5.1.1 on 2024-09-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_category_note_end_date_note_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
