# Generated by Django 5.1.1 on 2024-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
