# Generated by Django 5.1.1 on 2024-09-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_deletednote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedNote',
        ),
    ]
