# Generated by Django 5.1.1 on 2024-09-26 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_deletednote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
