# Generated by Django 5.1.1 on 2024-09-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_note_end_date_alter_note_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.ImageField(upload_to='notes_photos/'),
        ),
    ]
