# Generated by Django 5.1.1 on 2024-09-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_note_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.ImageField(default='default_event_photo.jpg', upload_to='notes_photos/'),
        ),
    ]
