# Generated by Django 5.1.1 on 2024-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_note_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
