# Generated by Django 5.1.1 on 2024-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_note_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('Environment', 'Environment'), ('Technology', 'Technology'), ('Design', 'Design'), ('Culture', 'Culture'), ('Business', 'Business'), ('Politics', 'Politics'), ('Travel', 'Travel')], default='Technology', max_length=50),
        ),
    ]
